
# docker-compose.yml
version: "3.3"
services:
  frontend:
    build:
      context: .
      dockerfile: "./Dockerfile-react"
    volumes:
      - ./go-movies:/go-movies
    command: >
      sh -c "npm run start"
    ports:
      - "3000:3000"
    container_name: "frontend"
